### ISSUE TITLE
Smart contract panicked: Signature request has timed out.

### ISSUE THREAD

**Issue by upendra-eth** [near-examples/near-multichain#33]
When i am trying to call sign function on contract. Iternal transection clear_state_on_finish failing. 
And final transection status is Success with msg - Smart contract panicked: Signature request has timed out.

**Comment by gagdiez** [comment]
yes, this happens when the `signer` contract times out, and there is not much we can do from the frontend side, except requesting the signature again, since it is the contract that is timing out
